### ISSUE TITLE
cannot import js object as value

### ISSUE THREAD

**Issue by noelzubin** [toddbluhm/env-cmd#114]
`
{
  "dev": {
      "key" : { "a": 1, "b" : 2 }
   }
}
`

if i say process.env.key this gives [object object]. shouldn't it give the object as is ?

or unparsed object string atleast ?

**Comment by noelzubin** [comment]
i think it should be stringified object.

**Comment by toddbluhm** [comment]
`env-cmd` currently does not support nested objects. It only supports strings, numbers, and booleans at this time. The recommended solution would be for your program to stringify that deeply nested object.
