### ISSUE TITLE
Failed to find .rc file at default paths: [./.env-cmdrc,./.env-cmdrc.js,./.env-cmdrc.json]

### ISSUE THREAD

**Issue by Waseemrajashaik** [toddbluhm/env-cmd#118]
I am trying to set environment variables

- Created .env-cmdrc file in src folder(create-react-app)
- Add Variables like 
```
{
 "dev": { "SOME_VAR": "VALUE"},
 "qa": { "SOME_VAR": "VALUE"},
}
```
in .env-cmdrc file
- In Package.json - changed `"start": "react-scripts start"` to `"start": "env-cmd dev react-scripts start"`
got error saying
```
Failed to find .env file at default paths: [./.env,./.env.js,./.env.json]
```
then changed command to ``"start": "env-cmd -e dev react-scripts start"``
got error saying
```
Failed to find .rc file at default paths: [./.env-cmdrc,./.env-cmdrc.js,./.env-cmdrc.json]
```

What should i do ?

**Comment by PerlBug** [comment]
Same issue

**Comment by maximiliano-gt** [comment]
any news about this? same issue 

My .env-cmdrc.json file looks like

`{
    "development": {
        "REACT_APP_BASE_PAGE_URL": "https://devurl.com"
    },
    "production": {
        "REACT_APP_BASE_PAGE_URL": "https://produrl.com"
    }
}`

`script : env-cmd --rc-file ./.env-cmdrc.json -e development, react-scripts build`

`Error: Error [PathError]: Failed to find .rc file at path: /myfolder/.env-cmdrc.json`
