### ISSUE TITLE
Fails to run any command?

### ISSUE THREAD

**Issue by sontek** [toddbluhm/env-cmd#13]
I'm trying to launch webpack with environment variables so in my `packages.json` I do:

```
env-cmd production webpack --bail
```

But this returns:

```
> env-cmd production webpack --bail

spawn webpack ENOENT
```

I assumed this was because it hasn't activated `node_modules/` in its path but even if I work around this:

```
./node_modules/env-cmd/bin/env-cmd.js production node ./node_modules/webpack/bin/webpack.js
spawn node ENOENT
```

The only thing that works is:

```
./node_modules/env-cmd/bin/env-cmd.js node ./node_modules/webpack/bin/webpack.js
```

but I have no idea what environment that is running?

**Comment by toddbluhm** [comment]
Thanks for reporting this! I just released a new version a few days ago and added in .env-cmdrc support so its probably a bug with that. I will take a look. In the mean time, does it work fine using a `.env` file instead of `.env-cmdrc`?

**Comment by toddbluhm** [comment]
Figured out the issue. I was not adding back in the system env vars after reading the `.env-cmdrc` file so the spawned command had no system paths etc... Fix should be up soon.

**Comment by toddbluhm** [comment]
Just published 4.0 which should fix this issue. Please re-open if its still not working.

**Comment by Remzes** [comment]
Hello!

@toddbluhm right now there is a version 8, and I cannot use it with create-react-app. I tried several times with a .env-cmdrc, but it gives me ENOENT for npm, node, and react-scripts

**Comment by j-e-clark** [comment]
@toddbluhm 
I was following a gatsby.js tutorial that recommended env-cmd and I couldn't work out why it wouldn't work for me.
He was using version 8.0.2 in the tutorial. I was using 9.0.2.
Reverting to version 8.0.2 resolved the issue.

**Comment by toddbluhm** [comment]
@j-e-clark @g1aurav the options have changed in `v9`. You have to pass a `-e` flag before passing in any environment names. This is most likely why reverting to `v8` worked for you. If you were using the `-e` flag and it was still broken, please consider opening a new support ticket with more details of your particular situation.

@Remzes I am sorry for not helping you sooner, I usually do not revisit old support tickets once they are closed. If you are still having issues on this, please open a new support ticket with details of your problem and even a link to this create-react-app project/tutorial.

**Comment by j-e-clark** [comment]
@toddbluhm Thanks for the response. In case anyone else gets to this page with the same issue my problem needed the `-f` flag before a custom env file path rather than the `-e` flag; but your response and the documentation got me to the solution. `v9` is now working for me. Thanks
