### ISSUE TITLE
Does env-cmd support this? How?

### ISSUE THREAD

**Issue by pronan** [toddbluhm/env-cmd#25]
Hello, if I run `env-cmd ./config.env webpack --progress`, I wish all variables defined in source `index.js` translated to correspondent constant in output `bundle.js` . e.g:

# config.env
```
FOO=foo
BAR=bar
```

# index.js
`var x = [ENV.FOO, ENV.BAR]`

# bundle.js 

`var x = ["foo", "bar"]`

**Comment by toddbluhm** [comment]
@pronan I think you mis-understand how webpack works. Webpack compiles existing js files into just one js file, so webpack needs to know what vars to replace. The above env vars your provided are sent to webpack, you have to tell webpack (via `webpack.config.js`) to replace those vars in your js files with the ones in the `config.env` file.

Look at https://webpack.js.org/plugins/define-plugin/ for more info. You will end up with something like this in your webpack config:
```js
plugins: [
  new webpack.DefinePlugin({
    "ENV.FOO": process.env.foo,  // process.env is a special nodejs object that holds all env vars
    "ENV.BAR": process.env.bar
  }),
]
```

**Comment by pronan** [comment]
I'll check that. Thank you!
