### ISSUE TITLE
Consider inline comments for .env files

### ISSUE THREAD

**Issue by crimsonvspurple** [toddbluhm/env-cmd#272]
Example:
```
SOMETHING = WHATEVER #THIS IS A COMMENT
```

It works like that in some other places and IDEs definitely highlight that part as comment but env-cmd considers the whole thing as value. Example: https://github.com/vlucas/phpdotenv#comments

Similar issue in dotenv: https://github.com/motdotla/dotenv/issues/484

**Comment by sorenhoyer** [comment]
This bug leaves a really bad first impression and should be prioritized.

**Comment by diminutivesloop** [comment]
Is there going to be a release to actually make this change available?

**Comment by k-yle** [comment]
> Is there going to be a release to actually make this change available?

That's a question for @toddbluhm, at this point I think we could start drafting a changelog for v11
