### ISSUE TITLE
how to set env var from CLI  that overrides matching var in  .env file?

### ISSUE THREAD

**Issue by noahehall** [toddbluhm/env-cmd#300]
I have a base .env file that I need to override without creating a gizillion other env files, or  creating an envfile with superhuman capabilities

ive tried
`NODE_ENV=production env-cmd runpoop.js`

however it doesnt replace the nodenev in the *.env* file

How do I do this? is it possible? 
[here is the specific npm script im trying to run](https://github.com/noahehall/nodeproto/blob/f473c7f05010fa42dd05fae703a06102ae7a720b/apps/client/package.json#L32)

**Comment by noahehall** [comment]
[here is my workaround until i find a better approach](https://github.com/noahehall/nodeproto/blob/5ebf745269a4899be9e83d5a6333616ab90147ce/libraries/utils/envproto/envvars.mjs#L15)


I had to rely on dotenv, as `env-cmd.GetEnvFromVars` thing returns a promise, and I cant use top-level await when outputing to cjs via esbuild (thus i cant use promises without other headaches)

Any guidance on this?

**Comment by fidgi** [comment]
Hi,

did you try --no-override option ?

regards,

**Comment by leite08** [comment]
I just used the `--no-override` option as suggested by @fidgi and it worked like a charm.

Just make sure to set the variable(s) on the same shell you're executing `env-cmd` or as an environment variable:
- shell variable: `ABC=123 env-cmd --no-override ...`
- environment variable: `export ABC=123 && env-cmd --no-override ...`

`ABC=123 && env-cmd --no-override ...` won't work, as it sets ABC in one shell and runs env-cmd on another.

**Comment by k-yle** [comment]
I'm going to close this issue because `--no-override` is now supported, and it sounds like the original problem has been solved. 

Feel free to re-open this if there are still issues
