### ISSUE TITLE
Space after environment var breaks script

### ISSUE THREAD

**Issue by pisaacs** [toddbluhm/env-cmd#32]
A space after the environment var breaks the script; however, a space after the equal sign still works... I am concerned about a common scenario, where one may set `ENV = VALUE` (space before and after the equal sign). 
```
# ENV2 breaks, while ENV3 works
ENV2 =FOR ALL
ENV3= THE FISH
```

**Comment by toddbluhm** [comment]
You make a good point. I will investigate this, but I won't promise anything. The reason `ENV3` works is because it is actually including the space in the env value. So the value of `ENV3` is ` THE FISH`.

**Comment by toddbluhm** [comment]
After having thought a long time on this (sorry it has been so long, I moved into a new house), I agree 
 I should be stripping spaces around the name of the env var. I will try to get a PR out for this soon.

**Comment by toddbluhm** [comment]
Closed in https://github.com/toddbluhm/env-cmd/pull/35

**Comment by toddbluhm** [comment]
Sorry this took so long to release, but 8.0.0 is finally released with the stripe out spaces around `=` implemented.
