### ISSUE TITLE
Error: Failed to find .env file at path: ./.env .development  at getEnvFile (/app/node_modules/env-cmd/dist/get-env-vars.js:40:19)

### ISSUE THREAD

**Issue by AngelHadzhiev** [toddbluhm/env-cmd#334]
Hey, 
I recently got this issue which apparently cannot recognize the env file and I have no idea why this happens. Any ideas? 

It happens in my dockerfile when built and ran.

**Comment by pete0959** [comment]
Same fault here - no answers yet

**Comment by temrb** [comment]
I also currently have this issue..

**Comment by joaovitor123jv** [comment]
Same issue here, no code changes from last build. Using docker image `node:14` from dockerhub

**Comment by AngelHadzhiev** [comment]
Hey, 

I see that you the same issue as I do. I did have it resolved by adding this dependency: 

`  "env-cmd": "^10.1.0" `

**Comment by joaovitor123jv** [comment]
A thousand thanks @AngelHadzhiev ! Your suggestion works like a charm. I was using version `"env-cmd": "^8.0.2"` before for some unknown reason.
