### ISSUE TITLE
Need more helpful message when .env.js has error

### ISSUE THREAD

**Issue by siva-sankaran** [toddbluhm/env-cmd#340]
When .env.js file throwing error like "Cannot find module '...' " , env-cmd  tells us that "Failed to find .env file at path: {filePath}". This message is not telling the real issue.  

Alternatively "Something went wrong when accessing env file path:  ${filePath}"  will be better. Can  someone add your comments or correct this message with better English ?

https://github.com/toddbluhm/env-cmd/blob/66f3fa398685b83ef089532af3de67cc82d7b3ac/src/get-env-vars.ts#L38

**Comment by k-yle** [comment]
This was fixed in #338
