### ISSUE TITLE
Received malformed response from registry for env-cmd

### ISSUE THREAD

**Issue by hussaindatabeat** [toddbluhm/env-cmd#350]
![WhatsApp Image 2022-05-19 at 5 51 28 PM](https://user-images.githubusercontent.com/88645114/169454418-1feb5167-c1af-4011-89a4-558ef0a9112c.jpeg)

Hi,
I'm getting the above issue while installing the packages using the Yarn. Please help me with this issue.
Thanks a lot in advance

**Comment by k-yle** [comment]
Hey, this error is caused by network issues, it's not an issue with this library itself
