### ISSUE TITLE
dollar sign substitution is not working if the .env file is located in a custom path 

### ISSUE THREAD

**Issue by KooWeiHao** [toddbluhm/env-cmd#362]
In a react project

- An environment file named as .env.uat is located at ./env.
- In the environment file, there's a variable with dollar sign value. Eg: REACT_APP_TEST=${TEST}
- The "start" script is having the following command, "env-cmd -f ./env/.env.uat react-scripts start".
- Run the "start" script as follow, "TEST=HELLO npm run start".
- However, the value shown in the app is "${TEST}", instead of "Hello".

**Comment by toddbluhm** [comment]
Yeah, so this program does not work that way. You are supposed to put the `HELLO` in your `.env` file. If you wish to pass environment variables via the command line`TEST=HELLO npm run start`, look at combining `env-cmd` with [`cross-env`](https://github.com/kentcdodds/cross-env)
