### ISSUE TITLE
Options to pass variables via CLI

### ISSUE THREAD

**Issue by kashifchoudhry** [toddbluhm/env-cmd#373]
This is working great when using environment files. However I do have a need where I want to pass env variables in the CLI for example if something like the following could be done, which I would like to use in my package.json script on a windows machine:

`env-cmd -p MYVAR=foo playwright test`

**Comment by itsmebasti** [comment]
are you looking for [cross-env](https://www.npmjs.com/package/cross-env) maybe?

**Comment by toddbluhm** [comment]
yes, I believe `cross-env` is what you are looking for. You can also combine both CLI's in one command to accomplish what you are looking if you want the best of both worlds.
