### ISSUE TITLE
env-cmd always returns with 1

### ISSUE THREAD

**Issue by eseliger** [toddbluhm/env-cmd#39]
Introduced in v8, `env-cmd` began to exit always with exit code 1.
This is due to the 

```js
proc.on('exit', TerminateParentProc)
```

which then always calls `process.exit(1)`

**Comment by lfalke** [comment]
I have the same issue, `npm` was showing an `ELIFECYCLE` error because of that. Had to revert back to v7 to have the npm scripts working without the error.

**Comment by bogdansoare** [comment]
also having this issue

**Comment by toddbluhm** [comment]
Just released `8.0.1` that should fix this issue. It should also properly propagate other termination signals between child and parent processes.

If you run into any more issues either reopen this issue or create a new issue. Thanks for reporting this so quickly everyone!

**Comment by nxmohamad** [comment]
Tried to use this package. I think I'm facing the issue. exits with code 1. Using `8.0.1`

**Comment by toddbluhm** [comment]
Can anyone else confirm this is still occurring for them?

**Comment by eseliger** [comment]
Working for me 🤔
