### ISSUE TITLE
Package removed from `npm`

### ISSUE THREAD

**Issue by ajmeese7** [toddbluhm/env-cmd#394]
The package was just taken off of `npm`, what's going on with that?

https://web.archive.org/web/20241208184125/https://www.npmjs.com/package/env-cmd

**Comment by toddbluhm** [comment]
I think NPM itself is having issues. I am unable to log in and searching for popular packages on npm also results in 404 pages

**Comment by ajmeese7** [comment]
Oh great, it's gonna be one of _those_ Sundays.

Good catch, thanks boss, appreciate you getting back to me so soon!

**Comment by ajmeese7** [comment]
Update, it's back up now!
