### ISSUE TITLE
Support multiple .env files?

### ISSUE THREAD

**Issue by laggingreflex** [toddbluhm/env-cmd#4]
Thoughts on supporting multiple `.env` files?

**Comment by toddbluhm** [comment]
Yeah I certainly would be open to that. Maybe have it support merging too in the style of  `Object.assign`? Thoughts?

**Comment by toddbluhm** [comment]
I think if we go this route we will need to do some sort of flag style then so we know exactly when the user has stopped adding env files and we can retain the default behavior (no flags) that is very simplistic and I like that. So maybe something like this for multiple files: `env-cmd -e file1.env file2.env file3.env -c node index.js` maybe? 

Then for the merging aspect, the file to the right will always override the file to the left, meaning that the files will be applied to process.env in order from left -> right.

**Comment by laggingreflex** [comment]
I've changed my mind on this. Most tools I've come across expect (and [even advocate](https://www.npmjs.com/package/dotenv#should-i-have-multiple-env-files)) single env file. Docker by default not only recognizes a single `.env`, it also requires less configuration, whereas its support for having any other file name, let alone multiple of them, [is limited](https://github.com/docker/compose/pull/3057#r73365997). 

For this reason I've chosen to go with single .env file, and if need be combine several beforehand. 

Also I realized you could just chain `env-cmd` command to load multiple files:

    env-cmd .env-dev env-cmd .env-test npm run tests
