### ISSUE TITLE
Ability to get the resulting env object

### ISSUE THREAD

**Issue by hbourzeix** [toddbluhm/env-cmd#40]
In some cases , to be coherent across all the tooling , I need the resulting env object programmatically rather than as env vars.

**Comment by toddbluhm** [comment]
Sorry for the terribly late reply.

Currently, I return the child process, but that was just because I could, I have no particular reason for doing so. I will instead return the new environment variables from the `EnvCmd`. I assume that's what you are asking for?

**Comment by toddbluhm** [comment]
This has been implemented in the new `9.0.0` release 🎉 This release also exposes a programmatic API to use as well.
