### ISSUE TITLE
Shorten the command line a little

### ISSUE THREAD

**Issue by corebreaker** [toddbluhm/env-cmd#42]
Sometimes commands have the same pattern, like this in thi _package.json_:
```javascript
{
...
  "scripts": {
    "cmd1": "env-cmd --fallback ./.env.local The-Command-1",
    "cmd2": "env-cmd --fallback ./.env.local The-Command-2",
    "cmd3": "env-cmd --fallback ./.env.local The-Command-3",
    "cmd4": "env-cmd --fallback ./.env.local The-Command-4",
    "cmd5": "env-cmd --fallback ./.env.local The-Command-5"
  },
...
}
```

That could help if this can be simplifed like that:
```javascript
{
...
  "scripts": {
    "cmd1": "env-cmd -d The-Command-1",
    "cmd2": "env-cmd -d The-Command-2",
    "cmd3": "env-cmd -d The-Command-3",
    "cmd4": "env-cmd -d The-Command-4",
    "cmd5": "env-cmd -d The-Command-5"
  },
...
}
```

With a new option `-d` and `--defaults` which define `--fallback ./env.local` as the default.

**Comment by toddbluhm** [comment]
I think your right we should probably add a shorter flag and have a default value for it. Probably something like `-f`. While I like the `defaults` name, it does not accurately describe the feature. When I hear `defaults` I think, "If I don't include this env value, then it will take on the value in the defaults file", which is not how the feature works at all.

**Comment by corebreaker** [comment]
You are right.
