### ISSUE TITLE
Look for .env-cmdrc.json as rc file as well, so that editors can properly identify file format.

### ISSUE THREAD

**Issue by ravshansbox** [toddbluhm/env-cmd#44]

**Comment by toddbluhm** [comment]
This seems to be a requested feature. A PR has been made for it: https://github.com/toddbluhm/env-cmd/pull/38 But no movement on it since I commented. I will consider taking this upon myself soon.

**Comment by toddbluhm** [comment]
This has been implemented in the new `9.0.0` release 🎉
