### ISSUE TITLE
Environmental variables unavailable via command line.

### ISSUE THREAD

**Issue by kaufmann42** [toddbluhm/env-cmd#46]
With file:
```
CLIENT_ID=somerandomeid
```

and command:
`./node_modules/.bin/env-cmd .env echo $CLIENT_ID`
the result is an empty string. Am I missing anything here?

**Comment by toddbluhm** [comment]
At issue here is the fact that its pulling `$CLIENT_ID` from the current shell environment rather than from the process that `echo` is running in.  If you put `echo $CLIENT_ID` inside of a shell script (or any other script) it will work as expected.
