### ISSUE TITLE
Nothing seems to be happening

### ISSUE THREAD

**Issue by jordyvandomselaar** [toddbluhm/env-cmd#47]
I've installed env-cmd and added the following script:

`"env-cmd ./.env react-scripts start"`

My .env file is in the root of my project and contains the following data:

```
SOME_KEY=foo
```
Running `console.log(process.env.SOME_KEY);` shows `undefined`, however.

Is there anything I've missed?

**Comment by amityo** [comment]
I experience the same issue. can anyone comment if we run it correctly?

```
"test": "env-cmd ./tests/.env echo $TESTMODE",
```

**Comment by tomyates** [comment]
I'm getting the same result as @amityo

**Comment by andreialecu** [comment]
Was anyone able to figure out what is wrong? Seeing the same problem.

**Comment by amity0** [comment]
@tomyates @andreialecu I think that I was able to use it properly with something like this:
package.json:
```
"test:server": "cd dist/tests && env-cmd ../../envs/test.server.env mocha \"{.,!(node_modules)/**}/*.test.js\" 
```

**Comment by toddbluhm** [comment]
I have added some examples to demonstrate how to use the various options here: https://github.com/toddbluhm/env-cmd-examples

After looking at those, let me know if you are still having issues. If you are on Linux its possible there are still issues. A few others have reported issues on Linux, but it been very sporadic. I have used it on Linux successfully myself. The issues I have seen on Linux tend to be permission issues reading the `.env` file.

**Comment by andreialecu** [comment]
It was a problem with the way our project was set up. A babel plugin was embedding `process.env.VAR` as constants and `process.env` itself wouldn't contain anything. Was a problem on our end, we verified that this package works properly after all.

**Comment by toddbluhm** [comment]
Closing due to no additional feedback from other members.
