### ISSUE TITLE
[RFC] Possibility for multiple fallbacks

### ISSUE THREAD

**Issue by zomars** [toddbluhm/env-cmd#48]
I have these scripts in my `package.json`:

```
"start": "env-cmd ./.env.dev.local node server",
"start:prod": "env-cmd ./.env.local node server",
```

I would like the `.env.dev.local` to fallback to `.env.dev` and the `.env.local` to fallback to `.env` file. Is this possible?

**Comment by zomars** [comment]
Or maybe just declare it like this:

```
"start": "env-cmd ./.env.dev node server",
"start:prod": "env-cmd ./.env node server",
```

And make the script look first for the same file with a `.local` suffix and run that instead. Is this crazy talk? Please let me know.

**Comment by toddbluhm** [comment]
Very interesting idea. I plan to rethink/refactor how the fallback stuff works and I will keep this in mind for when I get the time to start that. Thanks for the suggestion. I am going to close this for now as I have seen it and won't change anything right this minute, but if you have other input along theses like feel free to add more comments to this issue or create a new one! Thanks again for the great feedback!

**Comment by zomars** [comment]
Thank you for the response!
