### ISSUE TITLE
Fallback does not work for my use case

### ISSUE THREAD

**Issue by silentlight** [toddbluhm/env-cmd#49]
I am trying to have .env.local fallback to .env.development. 

I tried `env-cmd ./.env.local --fallback ./.env.development node src/server/index.js`

but it does not work.

Is there a way to make it work?

**Comment by toddbluhm** [comment]
At this time the `--fallback` option does not allow specifying the name of the fallback file. I am looking at revamping all of this at some point, but just need to find the time and come up with a decent implementation as well. The fall backfile must be named `.env`.
