### ISSUE TITLE
[FEATURE REQUEST] Support comments in .env-cmdrc file

### ISSUE THREAD

**Issue by cweekly** [toddbluhm/env-cmd#53]
I know JSON doesn't allow comments, but does the rc file really have to be strict JSON?
It'd be nice to be able to comment there.

**Comment by toddbluhm** [comment]
I will consider adding this. My big hesitation is that I try to keep this relatively dependency free, but I think I have found a safe and dependency free json parser with comments lib that might work. I am in the process of a big rewrite so now might be the time to add it.

**Comment by toddbluhm** [comment]
At this time, I have decided against comments in `.json` files. I apologize for the delay in resolving this, but you can use a regular `.js` file and just export an object from that file. Then you can add all the comments you want 😄
