### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by elie222** [toddbluhm/env-cmd#61]
This is a bug in the latest version of this package. Works fine with 8.0.2, but not with 9.0.1.

I have a Create React App and run this command:

```json
    "build:test": "env-cmd .env.test yarn run build",
```

I get the following error:

```
spawn .env.test ENOENT
/bin/sh: line 1: 58663 Hangup: 1               env-cmd .env.test yarn run build
```

**Comment by g1aurav** [comment]
@elie222 I faced the same issue earlier today, I was able to make it work by downgrading my node version from `10.5.0` to `8.15.0`

**Comment by toddbluhm** [comment]
The options have changed in v9. You need to pass the `-f` flag if you want to provide a custom `.env` file path (by default it looking for `./.env` file). I will update the Readme to make that more apparent. Thanks for bringing this up. It was not a change I made lightly, but was necessary to better future proof the lib.

**Comment by ItsLeeOwen** [comment]
When specifying a `-f` with relative path, should it be relative to the ./node_modules/env-cmd/... directory, or the project working directory?

**Comment by toddbluhm** [comment]
It should be relative to where you executed the script from (so working directory).

**Comment by toddbluhm** [comment]
Closing due to inactive/no response from original poster.
