### ISSUE TITLE
Error: Unable to locate env file at default location (./.env)

### ISSUE THREAD

**Issue by flppv** [toddbluhm/env-cmd#64]
From some point I can't run `yarn build`, with that error. The last thing I updates was node version, rolling back to old one doesn't help, so I am not sure this is the reason. Any way to fix this? I have `.env.staging` file in the root directory.

**Comment by toddbluhm** [comment]
The options have changed in v9. You need to pass the `-f` flag if you want to provide a custom env file or path (by default with no `-f` flag it looks for `./.env file`).

**Comment by flppv** [comment]
@toddbluhm thanks! It worked. I was never working with `env-cmd` directly, it was provided by `yarn build` command, will rewrite my `package.json` now
