### ISSUE TITLE
Inability to locate an env file doesn't result in error code

### ISSUE THREAD

**Issue by blagh** [toddbluhm/env-cmd#66]
We're using env-cmd in our build process, and the most recent change to require a `-f` parameter for a custom env file location _should_ have failed our builds. 

Unfortunately it didn't, it just displays a warning in our build output, and CircleCI still marked it as a passing build, even though we hadn't actually deployed anything:

<img width="1271" alt="Screen Shot 2019-05-16 at 2 01 32 PM" src="https://user-images.githubusercontent.com/5570885/57876488-6d819080-77e3-11e9-9470-735b4a1f1fef.png">

Looks like this behaviour is already deprecated (DEP0018) and will be fixed in Node.js someday, but in the meanwhile it would be helpful if `env-cmd` signalled Node to return a non-zero exit status.

  [1]: https://github.com/toddbluhm/env-cmd/blob/b7cb14651b38f17da4a7eca9f447bf23d20f0b79/src/env-cmd.ts#L33

**Comment by toddbluhm** [comment]
Thank you so much for reporting this! This has been fixed and released in `9.0.2`
