### ISSUE TITLE
Pass private environment variables as arguments to npm scripts

### ISSUE THREAD

**Issue by deadcoder0904** [toddbluhm/env-cmd#91]
Basically, [this example](https://github.com/toddbluhm/env-cmd-examples/issues/3) pretty much sums up what I want to do.

Although, I'll provide you with my use-case.

I have a secret key called `API_KEY` that I want to access inside of `package.json`'s `scripts`.

# package.json

```json
{
   "scripts": {
      "start": "web-ext run --api-key=API_KEY"
   }
}
```

My `.env` file contains `API_KEY` which I want to keep private:

```bash
API_KEY=abc123
```

Now if I use `cmd-env`, I can't pass it as an argument to `--api-key`

I want the following to work 👇

```json
{
   "scripts": {
      "start": "cmd-env web-ext run --api-key=$API_KEY"
   }
}
```

Any way to add that?

**Comment by BinaryShrub** [comment]
I think we are both trying to do the same thing, I'm looking for an answer as well

https://github.com/toddbluhm/env-cmd/issues/93

**Comment by deadcoder0904** [comment]
Anyways I do it like

```sh
$ API_KEY=mysecretkey123 yarn start
```

But it only works on Unix system (Linux & Mac) I think. Windows not supported as it's bash where variables can be $SOMETHING.

So this works for me now but I'd love to have a cross-platform alternative like so :)

**Comment by BinaryShrub** [comment]
I think I have a solve that might work for you, check out my comment in my thread.

**Comment by toddbluhm** [comment]
Hey sorry for taking so long to reply to this.

The original goal was for the `--use-shell` option to be able to enable the functionality of replacing `$VAR` similar to how `cross-env` does it here: https://github.com/kentcdodds/cross-env#cross-env-vs-cross-env-shell. Unfortunately, that does not seem to work as expected. 

I tried a couple of different ways to make it work, but no dice. I think what I am going to have to do is implement some sort of parsing of the full shell command before execution and manually replace `$VAR` and `${VAR}` and `%VAR%` (windows) with the final env value. Not sure how well this will work, but it is a start.

**Comment by ProLoser** [comment]
@toddbluhm I'm curious since I'm seeing this question everywhere, does this work?
```
"scripts": {
	"start": "web-ext run --api-key=$API_KEY",
	"prestart": "cmd-env"

}
```

NPM always runs `prewhatever` before `whatever` (this works for any npm script), I wonder if the shell executions would be ordered correctly?

**Comment by toddbluhm** [comment]
@ProLoser I have never tried that nor did I know about the `prestart` script. Feel free to try it and report back if it works or not. With that said, using `prestart` with `env-cmd` in that manner is not a planned supported use case...though it would be awesome if it  "just worked"!

**Comment by luckylooke** [comment]
Following wants to be temporary solution, but id did not work for me, but it has upvotes, so it seems that it worked for some.
```
"env-cmd ./.config/prod.env cross-env-shell \"docker volume create $DOCKER_VOLUME\""
```
Source: https://stackoverflow.com/a/56280195/861615

I have tried:
*.env*
```
EXAMPLE=12345
```
*package.json*
```
"scripts": {
     "example": "env-cmd cross-env-shell \"echo $EXAMPLE\""
}
```
outputs
```
> env-cmd cross-env-shell "echo $EXAMPLE"
```

then I have tried with "./.env"

*package.json*
```
"scripts": {
     "example": "env-cmd ./.env cross-env-shell \"echo $EXAMPLE\""
}
```
output
```
> env-cmd ./.env cross-env-shell "echo $EXAMPLE"
spawn ./.env EACCES
[1]    91332 hangup     npm run example
```

another trywith ".env"
*package.json*
```
"scripts": {
     "example": "env-cmd .env cross-env-shell \"echo $EXAMPLE\""
}
```
```
output
```
> env-cmd .env cross-env-shell "echo $EXAMPLE"
spawn .env ENOENT
[1]    90718 hangup     npm run example
```

also tried "-f .env" and "-f ./.env"
*package.json*
```
"scripts": {
     "example": "env-cmd -f .env cross-env-shell \"echo $EXAMPLE\""
}
```
output
```
> env-cmd -f .env cross-env-shell "echo $EXAMPLE"
```
*package.json*
```
"scripts": {
     "example": "env-cmd -f ./.env cross-env-shell \"echo $EXAMPLE\""
}
```
output
```
> env-cmd -f ./.env cross-env-shell "echo $EXAMPLE"
```

I do not know what I am doing wrong here :D
Thanks for any hint or temporary solution how can I use secret variable from .env file in npm script :)

**Comment by omeid** [comment]
@toddbluhm Have you considered using the `shell` feature of the `cross-env` instead of re-implementing it?

https://github.com/kentcdodds/cross-env/blob/67f21c32543af0ecdbaf2508d620d81d3307a433/src/variable.js#L31-L59

**Comment by toddbluhm** [comment]
@omeid interesting idea, but I do not use `cross-env` in the package and I would rather not add an additional dependency, unless absolutely necessary. I liked your PR so I merged that one.
